#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : perl-JSON-Any
Version  : 1.40
Release  : 22
URL      : https://cpan.metacpan.org/authors/id/E/ET/ETHER/JSON-Any-1.40.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/E/ET/ETHER/JSON-Any-1.40.tar.gz
Summary  : '(DEPRECATED) Wrapper Class for the various JSON classes'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-JSON-Any-license = %{version}-%{release}
Requires: perl-JSON-Any-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Test::Fatal)
BuildRequires : perl(Test::Needs)
BuildRequires : perl(Test::Warnings)
BuildRequires : perl(Test::Without::Module)
BuildRequires : perl(Try::Tiny)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This archive contains the distribution JSON-Any,
version 1.40:
(DEPRECATED) Wrapper Class for the various JSON classes

%package dev
Summary: dev components for the perl-JSON-Any package.
Group: Development
Provides: perl-JSON-Any-devel = %{version}-%{release}
Requires: perl-JSON-Any = %{version}-%{release}

%description dev
dev components for the perl-JSON-Any package.


%package license
Summary: license components for the perl-JSON-Any package.
Group: Default

%description license
license components for the perl-JSON-Any package.


%package perl
Summary: perl components for the perl-JSON-Any package.
Group: Default
Requires: perl-JSON-Any = %{version}-%{release}

%description perl
perl components for the perl-JSON-Any package.


%prep
%setup -q -n JSON-Any-1.40
cd %{_builddir}/JSON-Any-1.40
pushd ..
cp -a JSON-Any-1.40 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-JSON-Any
cp %{_builddir}/JSON-Any-%{version}/LICENCE %{buildroot}/usr/share/package-licenses/perl-JSON-Any/b4c9db4e0d07a2ad71662fde4f25a196a50309c4 || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/JSON::Any.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-JSON-Any/b4c9db4e0d07a2ad71662fde4f25a196a50309c4

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
